### ISSUE TITLE
Number of works isn't displaying.

### ISSUE THREAD

**Issue by owendodd** [artsy/flare#23]
![screen shot 2015-06-25 at 4 30 02 pm](https://cloud.githubusercontent.com/assets/3196536/8392545/f3c27e52-1cbb-11e5-9fdb-7f72552507ff.png)

**Comment by dzucconi** [comment]
![](http://static.damonzucconi.com/_capture/5y/s2p88eyn0ggks.png)

**Comment by owendodd** [comment]
Weird, seems to be fine now but I have been experiencing it on and off for quite awhile.

**Comment by dzucconi** [comment]
@owendodd sorry I just meant to close this. This was fixed but not deployed. Just re-deployed today. Thanks for the bump.

**Comment by owendodd** [comment]
ahh got it. ok cool. Thanks!
